os: osx
language: cpp
compiler: clang
before_install:
  - brew update
install:
  - brew install sdl2
  - brew install openal-soft
  - brew install enet
  - brew install jpeg
before_script: ./autogen.sh
script:
  - export CPPFLAGS='-I/usr/local/include'
  - export LDFLAGS='-L/usr/local/lib'
  - mkdir build && cd build && ../configure && make
